api/index.ts, server/project/collection.ts, server/project/middleware.ts, server/project/model.ts, server/project/router.ts, server/project/util.ts
Create backend for project, allowing users to:
- view all projects a user has
- create a project
- archive a project
- modify a project 
- invite users to a project (through modify endpoint)
- accept/reject invites to a project
also validates the calls to endpoints
=> Project backend

client/App.vue, client/components/Project/AddProjectComponent.vue, client/components/Project/InviteComponent.vue, client/components/Project/ProjectDashboard.vue, client/components/Project/ProjectInvitesComponent.vue, client/components/common/Modal.vue, client/store.ts
Currently uses hard-coded invites
=> Add forms for adding proj/handling invites

server/user/middleware.ts, server/user/router.ts
Fixes some small bugs in creating a user that allow ```undefined``` to get past the middleware for checking a new user's email, password, and names, which then crash the server :(
=> Fix user creation

client/App.vue, client/components/Home/HomePage.vue, client/components/Project/AddProjectComponent.vue, client/components/Project/InviteComponent.vue, client/components/Project/ProjectComponent.vue, client/components/Project/ProjectDashboard.vue, client/components/Update/UpdatePreview.vue, client/components/Update/UpdatesPage.vue, client/router.ts, client/store.ts, server/project/collection.ts, server/project/middleware.ts, server/project/router.ts, server/project/util.ts, server/user/collection.ts
- Implemented`All` view for updates
- Fixed bugs with project backend
- Fixed bug with user collection that queried by username instead of email
- Made POST route for projects take in a list of emails instead and update validators
- Replaced projects/invites frontend with backend
=> Implement ALL view for updates; Integrate projects/invites with backend; Fix misc bugs

client/components/Project/ProjectComponent.vue, client/components/Update/AddUpdatePage.vue, client/components/Update/GetCurrentProject.vue, client/components/Update/UpdatePreview.vue, client/components/Update/UpdatesPage.vue, client/router.ts, client/store.ts, server/update/util.ts
=> Implement form to add updates; Connect to updates backend

client/App.vue, client/components/Project/ProjectComponent.vue, client/components/Update/UpdateDetailPage.vue, package-lock.json, package.json
- Only creators of projects can archive. Edit button not visible otherwise
- Archiving is permanent for now
=> Add ability to archive project

api/index.ts, server/thanks/collection.ts, server/thanks/middleware.ts, server/thanks/model.ts, server/thanks/router.ts, server/thanks/util.ts
takes [ff68974](https://github.com/opheeelia/standup/commit/ff68974241417b88d4309654707ca64269d23969) and adds thanksRouter to the application in order to avoid big merge conflicts
=> Thanks backend

client/App.vue, client/components/EyesWanted/AddEyesWanted.vue, client/components/Home/HomePage.vue, client/components/Home/Readinglist.vue, client/components/Thanks/AddThanks.vue, client/components/Update/AddUpdatePage.vue, client/components/Update/UpdateDetailPage.vue, client/components/Update/UpdatePreview.vue, client/store.ts, server/eyeswanted/collection.ts, server/eyeswanted/router.ts, server/thanks/collection.ts, server/thanks/middleware.ts, server/thanks/model.ts, server/thanks/router.ts, server/thanks/util.ts, server/update/middleware.ts
Everything except the last commit on ```eyeswanted-frontend```
=> Beta merge

client/components/Project/ProjectComponent.vue, client/components/Project/ProjectDashboard.vue, client/components/Update/UpdatesPage.vue, client/components/common/Modal.vue, server/project/collection.ts, server/project/router.ts
Attempting to delete will open a warning first since the action is more permanent
Fixes #22
=> Enable reactivating/deleting a project

client/App.vue, client/components/Account/AccountPage.vue, client/components/Account/AccountSettingsPage.vue, client/components/EyesWanted/AddEyesWanted.vue, client/components/EyesWanted/CompleteEyesWanted.vue, client/components/Thanks/AddThanks.vue, client/components/Update/UpdateDetailPage.vue, client/components/Update/UpdatePreview.vue, client/router.ts, client/store.ts, server/eyeswanted/collection.ts, server/eyeswanted/middleware.ts, server/eyeswanted/router.ts, server/eyeswanted/util.ts, server/thanks/middleware.ts, server/thanks/router.ts
done:
reading list
mark read
add/remove eyes wanted
add/remove thanks
todo:
allow users to see who has viewed "eye wanted" items
=> Eyeswanted&thanks frontend

client/components/Update/AddUpdatePage.vue, client/components/Update/UpdateDetailPage.vue, client/components/Update/UpdateForm.vue
- Refactored form from AddUpdateForm
- Enables saves only if the content has changed
=> Enable editing of updates

client/App.vue, client/components/Project/ProjectComponent.vue, client/components/Update/AddUpdatePage.vue, client/components/Update/UpdateDetailPage.vue, client/components/Update/UpdatePreview.vue, client/components/Update/UpdateSidebar.vue, client/components/Update/UpdatesPage.vue, client/components/Update/views/AllUpdatesView.vue, client/components/Update/views/UserView.vue, client/router.ts, client/store.ts
=> Create sidebar for navigating between views; Implement User View

server/project/collection.ts, server/project/middleware.ts, server/project/model.ts, server/project/router.ts, server/project/util.ts, server/update/collection.ts, server/update/middleware.ts, server/update/model.ts, server/update/router.ts, server/update/util.ts
Adds ```tags``` field to ```Project``` and ```Update```.
Tags are filtered, trimmed for whitespace, and set to all lowercase, with duplicates dropped, in ```router.ts```.
Removing a tag from a project will remove that tag from all updates with it.
Updates can only be given tags that are in the project's tag space.
=> Implement backend for tags

client/components/Home/HomePage.vue, client/components/Home/Readinglist.vue, client/components/Project/ProjectDashboard.vue, client/components/Update/UpdateDetailPage.vue, client/components/Update/UpdateForm.vue, client/components/common/NavBar.vue, client/router.ts, server/user/router.ts
- Rename update creation form and other references to "Action Items" to change to "Next Steps" when the update status is completed
- Automatically add new users to a global project (with id 639179ef023b81d034a808c1)
- Merge the home page and project dashboard, make eyes wanted list scrollable
=> Feedback changes

client/App.vue, client/components/EyesWanted/AddEyesWanted.vue, client/components/EyesWanted/CompleteEyesWanted.vue, client/components/Home/Readinglist.vue, client/components/Thanks/AddThanks.vue, client/components/Thanks/ThanksCount.vue, client/components/Update/UpdateDetailPage.vue, client/components/Update/UpdatePreview.vue, client/store.ts, server/eyeswanted/router.ts
- Only fetch thanks & eyeswanted from projects that the user is involved with (formerly fetched all from the database)
- Make thanks text more condensed
- Make thanks button appear toggleable
- Change styling of status tags so that they look distinct from buttons
- Improve linguistics of eyeswanted
- Highlight eyeswanted updates
=> Refactor and improve UX of thanks/eyeswanted

server/project/middleware.ts
=> Don't allow invite self

client/components/Project/AddProjectComponent.vue, server/project/util.ts, server/thanks/util.ts, server/user/util.ts
=> Fix project date bug and cleanup unused formatDate

client/components/Project/InviteComponent.vue, server/eyeswanted/collection.ts, server/project/router.ts
When a user accepts an invite to a project, adds them to every Eyes Wanted that has existed for any update in the project.
#52
=> Add users who just accepted an invite to all Eyes Wanted

client/App.vue, client/components/Update/UpdateDetailPage.vue
=> Show update delete warning; handle overflowing update

client/components/Project/ProjectDashboard.vue
=> Move add proj btns to under header

client/App.vue, client/components/Project/AddProjectComponent.vue, client/components/Update/AddUpdatePage.vue, client/components/Update/UpdateDetailPage.vue, client/components/Update/UpdateForm.vue, client/components/Update/UpdatePreview.vue, client/components/common/TextInput.vue, client/store.ts, server/eyeswanted/router.ts, server/project/middleware.ts
Resolves #20 
- Added validation
- Reduce tag char limit to 20
=> Add validation to update and project forms

client/components/Update/UpdateSidebar.vue
=> Fade overflow of tabs
